version: '3.3'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/obapi
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    networks:
      - spring-net

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: obapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5433
    networks:
      - spring-net

volumes:
  db-data:

networks:
  spring-net:
    driver: bridge
